### ISSUE TITLE
Pod Crashlooping due to GET request to Azure DevOps project is failing

### ISSUE THREAD

**Issue by derekkl** [bfarr-rh/azure-devops-ocp-agent#1]
I was able to create the templates, build the docker image, and deploy the BC and deployment via the templates.

However, the pod is crashlooping due to this error when trying to reach my Azure DevOps project:

[2022-01-13 17:12:46Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2022-01-13 17:12:47Z ERR  VisualStudioServices] GET request to https://dev.azure.com/CableOne-ProductDevelopers/DevOpsDerek/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. HTTP Status: NotFound, AFD Ref: Ref A: 372D1668B0A241C38AAAD1B940380E0A Ref B: SN1EDGE1709 Ref C: 2022-01-13T17:12:47Z

This has been replicated by a teammate of mine, they are having the same issue when trying to reach their project.

I am able to connect to the project via a normal curl command, I'm not sure what it is appending to this endpoint that is making it 404 page not found. 

Here's a curl command from a debug of the Azure Devops pod that is running.

sh-4.4$ curl -v https://dev.azure.com/CableOne-ProductDevelopers/DevOpsDerek
*   Trying 13.107.42.20...
* TCP_NODELAY set
* Connected to dev.azure.com (13.107.42.20) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=dev.azure.com
*  start date: Nov  9 16:14:27 2021 GMT
*  expire date: Nov  9 16:14:27 2022 GMT
*  subjectAltName: host "dev.azure.com" matched cert's "dev.azure.com"
*  issuer: C=US; O=Microsoft Corporation; CN=Microsoft RSA TLS CA 02
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x556c8198e8b0)
> GET /CableOne-ProductDevelopers/DevOpsDerek HTTP/2
> Host: dev.azure.com
> User-Agent: curl/7.61.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 302
< cache-control: no-cache, no-store, must-revalidate
< pragma: no-cache
< content-length: 605
< content-type: text/html; charset=utf-8
< expires: -1
< location: https://spsprodcus1.vssps.visualstudio.com/_signin?realm=dev.azure.com&reply_to=https%3A%2F%2Fdev.azure.com%2FCableOne-ProductDevelopers%2FDevOpsDerek&redirect=1&hid=56a8e117-ac45-4594-8e20-d329cfe98b9f&context=eyJodCI6MiwiaGlkIjoiOTkyOGQ5YzUtNmU0Mi00NDJmLTg5YmYtNGQwZDI3YTFiYWI2IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2
< p3p: CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
< set-cookie: VstsSession=%7B%22PersistentSessionId%22%3A%22e1ef32e2-b4ad-40bf-af8c-8a28a25fde6c%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22SignInState%22%3A%7B%7D%7D;SameSite=None; domain=.dev.azure.com; expires=Fri, 13-Jan-2023 19:57:58 GMT; path=/; secure; HttpOnly
< www-authenticate: Bearer authorization_uri=https://login.microsoftonline.com/d283f563-83f4-4d65-a9d1-028758bd1572
< www-authenticate: Basic realm="https://tfsprodcus3.visualstudio.com/"
< x-tfs-processid: 71e65cbe-6316-4e27-a8d2-b61417946643
< strict-transport-security: max-age=31536000; includeSubDomains
< activityid: 13587fd5-4e18-4650-889f-2c11135bf0e5
< x-tfs-session: 13587fd5-4e18-4650-889f-2c11135bf0e5
< x-vss-e2eid: 13587fd5-4e18-4650-889f-2c11135bf0e5
< x-vss-senderdeploymentid: 371dc223-5e58-9481-da2c-e75ac4f20939
< x-frame-options: SAMEORIGIN
< x-tfs-fedauthrealm: https://tfsprodcus3.visualstudio.com/
< x-tfs-fedauthissuer: https://dev.azure.com/CableOne-ProductDevelopers/
< x-vss-authorizationendpoint: https://vssps.dev.azure.com/CableOne-ProductDevelopers/
< x-vss-resourcetenant: d283f563-83f4-4d65-a9d1-028758bd1572
< x-tfs-soapexception: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20The%20user%20%27%27%20is%20not%20authorized%20to%20access%20this%20resource.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
< x-tfs-serviceerror: TF400813%3A%20The%20user%20%27%27%20is%20not%20authorized%20to%20access%20this%20resource.
< x-vss-s2stargetservice: 00000002-0000-8888-8000-000000000000/visualstudio.com
< request-context: appId=cid-v1:f88d1338-e7ba-4d7b-83e0-e573c40a2f62
< access-control-expose-headers: Request-Context
< x-content-type-options: nosniff
< x-cache: CONFIG_NOCACHE
< x-msedge-ref: Ref A: C91F913265C34D1AA8FA87C7F2C922D2 Ref B: SN1EDGE1709 Ref C: 2022-01-13T19:57:58Z
< date: Thu, 13 Jan 2022 19:57:58 GMT
<
<html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="https://spsprodcus1.vssps.visualstudio.com/_signin?realm=dev.azure.com&amp;reply_to=https%3A%2F%2Fdev.azure.com%2FCableOne-ProductDevelopers%2FDevOpsDerek&amp;redirect=1&amp;hid=56a8e117-ac45-4594-8e20-d329cfe98b9f&amp;context=eyJodCI6MiwiaGlkIjoiOTkyOGQ5YzUtNmU0Mi00NDJmLTg5YmYtNGQwZDI3YTFiYWI2IiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSIsImh0dHBzOi8vbG9naW4ubWljcm9zb2Z0b25saW5lLmNvbSJdfQ2">here</a>.</h2>
</body></html>
* Connection #0 to host dev.azure.com left intact

**Comment by bfarr-rh** [comment]
Hi - from a connection point of view the only parameters concerned I believe are these ones below that you specify in the template. I haven't come across this issue yet - but had some issues early on only when either the token was invalid or the Agent Pool name didnt match to the one setup.
- description: Azure DevOps instance
  name: AZP_URL
  required: true  
- description: Azure DevOps Pool name
  name: AZP_POOL
  required: true
  value: ""
- description: Azure DevOps Agent Personal Access Token
  name: AZP_TOKEN
  required: true

**Comment by derekkl** [comment]
I found the problem. I was using the entire project URL 
https://dev.azure.com/CableOne-ProductDevelopers/DevOpsDerek 
rather than the organization URL 
https://dev.azure.com/CableOne-ProductDevelopers/.

The verbiage in the guide threw me off, I think

"Setup a project in Azure Devops and get the **project** based URL ($AZP_URL) . For example https://dev.azure.com/Organisation_Name"

I see the link shows clearly it should be the Organization_Name, but I used the Project URL.

**Comment by bfarr-rh** [comment]
Thanks! Updated the guide.
